version: '3'

networks:
  wordpress:
    driver: bridge

volumes:
  app:
  my:

services:
  webproxy:
    image: amelus99/nginx-lb:1.0
    networks:
      - wordpress
    ports:
      - "8080:8080"
    depends_on:
      - webserver

  webserver:
    image: wordpress:latest
    networks:
      - wordpress
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - app:/var/www/html

  database:
    image: mysql:5.7
    networks:
      - wordpress
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpresspassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - my:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

