---
- name: Provisionar Servidor Completo
  hosts: all
  become: true

  tasks:
    - name: Atualizar cache do apt
      apt:
        update_cache: yes

    - name: Alterar hostname
      hostname:
        name: server.samuel.Isabel

    - name: Instalar pacotes básicos
      apt:
        name:
          - curl
          - vim
        state: present

    - name: Instalar dependências do Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Adicionar chave GPG do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar repositório oficial do Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present
        filename: docker

    - name: Atualizar cache do apt após adicionar repositório
      apt:
        update_cache: yes

    - name: Instalar Docker e Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: present

    - name: Iniciar e habilitar serviço do Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Adicionar usuário vagrant ao grupo docker
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Copiar docker-compose.yml para a VM
      copy:
        src: docker-compose.yml
        dest: /home/vagrant/docker-compose.yml

    - name: Subir infraestrutura Docker
      command: docker-compose up -d
      args:
        chdir: /home/vagrant/
